<?php
/**
 * This is the template for generating the model class of a specified table.
 * - $this: the ModelCode object
 * - $tableName: the table name for this class (prefix is already removed if necessary)
 * - $modelClass: the model class name
 * - $columns: list of table columns (name=>CDbColumnSchema)
 * - $labels: list of attribute labels (name=>label)
 * - $rules: list of validation rules
 * - $relations: list of relations (name=>relation declaration)
 * - $representingColumn: the name of the representing column for the table (string) or
 *   the names of the representing columns (array)
 */
 
$words = preg_split('/(?=[A-Z])/', $modelClass, -1, PREG_SPLIT_NO_EMPTY);
$underlined = strtolower(implode('_', $words));

$indexColumn = empty($indexColumn) ? null : $indexColumn;

?>
<?php echo "<?php\n"; ?>

/**
 * This is the model base class for the table "<?php echo $tableName; ?>".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "<?php echo $modelClass; ?>".
 *
 * Columns in table "<?php echo $tableName; ?>" available as properties of the model,
<?php if(!empty($relations)): ?>
 * followed by relations of table "<?php echo $tableName; ?>" available as properties of the model.
<?php else: ?>
 * and there are no model relations.
<?php endif; ?>
 *
<?php foreach($columns as $column): ?>
 * @property <?php echo $column->type.' $'.$column->name."\n"; ?>
<?php endforeach; ?>
 *
<?php foreach(array_keys($relations) as $name): ?>
 * @property <?php
	$relationData = $this->getRelationData($modelClass, $name);
	$relationType = $relationData[0];
	$relationModel = $relationData[1];

	switch($relationType) {
		case GxActiveRecord::BELONGS_TO:
		case GxActiveRecord::HAS_ONE:
			echo $relationModel;
			break;
		case GxActiveRecord::HAS_MANY:
		case GxActiveRecord::MANY_MANY:
			echo $relationModel . '[]';
			break;
		default:
			echo 'mixed';
	}
	echo ' $' . $name . "\n";
	?>
<?php endforeach; ?>
 */
abstract class <?php echo $this->baseModelClass; ?> extends <?php echo $this->baseClass; ?> {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '<?php echo $tableName; ?>';
	}

	public static function label($n = 1) {
		return Yii::t('model', '<?php echo implode(' ', $words); ?>|<?php echo $this->pluralize(implode(' ', $words)); ?>', $n);
	}

    public static function indexColumn() {
<?php if (is_array($indexColumn)): ?>
        return array(
<?php foreach($indexColumn as $indexColumn_item): ?>
            '<?php echo $indexColumn_item; ?>',
<?php endforeach; ?>
        );
<?php else: ?>
        return '<?php echo $indexColumn; ?>';
<?php endif; ?>
    }

	public static function representingColumn() {
<?php if (is_array($representingColumn)): ?>
		return array(
<?php foreach($representingColumn as $representingColumn_item): ?>
			'<?php echo $representingColumn_item; ?>',
<?php endforeach; ?>
		);
<?php else: ?>
		return '<?php echo $representingColumn; ?>';
<?php endif; ?>
	}

	public function rules() {
		return array(
<?php foreach($rules as $rule): ?>
			<?php echo $rule.",\n"; ?>
<?php endforeach; ?>
			array('<?php echo implode(', ', array_keys($columns)); ?>', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
<?php foreach($relations as $name=>$relation): ?>
			<?php echo "'{$name}' => {$relation},\n"; ?>
<?php endforeach; ?>
		);
	}

	public function pivotModels() {
		return array(
<?php foreach($pivotModels as $relationName=>$pivotModel): ?>
			<?php echo "'{$relationName}' => '{$pivotModel}',\n"; ?>
<?php endforeach; ?>
		);
	}

	public function attributeLabels() {
		return array(
<?php foreach($labels as $name=>$label): ?>
<?php if($label === null): ?>
			<?php echo "'{$name}' => null,\n"; ?>
<?php else: ?>
			<?php echo "'{$name}' => {$label},\n"; ?>
<?php endif; ?>
<?php endforeach; ?>
		);
		
		/*
		array structure for translation:
		
//<?php echo str_replace('_',' ',str_replace('}','',str_replace('{','',$tableName))).PHP_EOL; ?>
	<?php 
echo "'".implode(' ', $words)."|".$this->pluralize(implode(' ', $words))."' => '".implode(' ', $words)."|".$this->pluralize(implode(' ', $words))."',".PHP_EOL;
	foreach($labels as $name=>$label) {
		if($label !== null) {
			$temp_label = ucwords(trim(strtolower(str_replace(array('-', '_'), ' ', preg_replace('/(?<![A-Z])[A-Z]/', ' \0', $name)))));
			$temp_label = preg_replace('/\s+/', ' ', $temp_label);
			$temp_value = str_replace(implode(' ', $words).' ','',$temp_label);
			if ($temp_value=="Id") {$temp_value='#';}
echo "'".$temp_label."' => '".$temp_value."',".PHP_EOL;
		}
	}
	?>
		*/
	}

	public function search() {
		$criteria = new CDbCriteria;
		
<?php $pk_column = null; ?>
<?php foreach($columns as $name=>$column): ?>
<?php $partial = ($column->type==='string' and !$column->isForeignKey); ?>
<?php if($name != ($underlined . '_deleted')) { ?>
		$criteria->compare('<?php echo $name; ?>', $this-><?php echo $name; ?><?php echo $partial ? ', true' : ''; ?>);
<?php if($column->isPrimaryKey) { $pk_column = $name; } ?>
<?php } else { $deleted_column = $name; } ?>
<?php endforeach; ?>

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			
			'pagination'=>array(
		        'pageSize' => Yii::app()->user->getState('pageSize', Yii::app()->params['defaultPageSize']),
		    ),
			
			'sort' => array(
			    'defaultOrder' => '<?php echo $pk_column; ?> DESC',
			),
		));
	}
	
	<?php
		if(!empty($deleted_column))
		{
			?>
			
    public function defaultScope()
    {
		$alias = $this->getTableAlias(false, false);
		
	    return array(
	       	'condition' => "$alias.<?php echo $deleted_column; ?> = 0",
	    );
    }
	
<?php } ?>
}